In [1]:
import pandas as pd
import os
import ast
import re

In [2]:
list_name = os.listdir('./')

In [3]:
list_name

['demo_script.ipynb',
 'LAB_codebook.csv',
 'LAB_dictionary_mapping.csv',
 'nhanes_codebook_lab_resultados.csv',
 'tabelas_lab_completas.csv']

In [4]:
nhanes_codebook = pd.read_csv('nhanes_codebook_lab_resultados.csv')

In [5]:
df_sem_duplicatas = nhanes_codebook.drop_duplicates()
df_sem_duplicatas

,Tabela,Variavel,Variable_Name,SAS_Label,English_Text,Target,English_Instructions,Tabela_Valores
0,L02HBS,SEQN,SEQN,Respondent sequence number,Respondent sequence number.,Both males and females 2 YEARS - 150 YEARS,NaN,NaN
1,L02HBS,LBXHBS,LBXHBS,Hepatitis B Surface Antibody,Hepatitis B surface antibody (anti-HBs),Both males and females 2 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti..."
2,L02HPA_A,SEQN,SEQN,Respondent sequence number,Respondent sequence number.,Both males and females 2 YEARS - 150 YEARS,NaN,NaN
3,L02HPA_A,LBXHA,LBXHA,Hepatitis A Antibody (Anti-HAV),Hepatitis A Antibody (Anti-HAV),Both males and females 2 YEARS - 150 YEARS,NaN,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti..."
4,LAB02,SEQN,SEQN,Respondent sequence number,Respondent sequence number.,Both males and females 6 YEARS - 150 YEARS,NaN,NaN
...,...,...,...,...,...,...,...,...
11544,VID_L,LBDVD2LC,LBDVD2LC,25OHD2 comment code,25-hydroxyvitamin D2 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."
11545,VID_L,LBXVD3MS,LBXVD3MS,25OHD3 (nmol/L),25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""4.1 to 422"", "".""]; Value.Descr..."
11546,VID_L,LBDVD3LC,LBDVD3LC,25OHD3 comment code,25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."
11547,VID_L,LBXVE3MS,LBXVE3MS,epi-25OHD3 (nmol/L),epi-25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0.54 to 62.8"", "".""]; Value.Des..."
11548,VID_L,LBDVE3LC,LBDVE3LC,epi-25OHD3 comment code,epi-25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."

In [6]:
df_sem_duplicatas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11549 entries, 0 to 11548
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Tabela                11549 non-null  object
 1   Variavel              11549 non-null  object
 2   Variable_Name         11549 non-null  object
 3   SAS_Label             11549 non-null  object
 4   English_Text          11491 non-null  object
 5   Target                11549 non-null  object
 6   English_Instructions  0 non-null      float64
 7   Tabela_Valores        10821 non-null  object
dtypes: float64(1), object(7)
memory usage: 721.9+ KB

In [7]:
df_sem_duplicatas[df_sem_duplicatas['Variavel']=='LBDVD3LC']

,Tabela,Variavel,Variable_Name,SAS_Label,English_Text,Target,English_Instructions,Tabela_Valores
5123,VID_E,LBDVD3LC,LBDVD3LC,25OHD3 comment code,25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."
6112,VID_F,LBDVD3LC,LBDVD3LC,25OHD3 comment code,25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."
7350,VID_G,LBDVD3LC,LBDVD3LC,25OHD3 comment code,25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."
8742,VID_H,LBDVD3LC,LBDVD3LC,25OHD3 comment code,25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."
10089,VID_I,LBDVD3LC,LBDVD3LC,25OHD3 comment code,25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."
11247,VID_J,LBDVD3LC,LBDVD3LC,25OHD3 comment code,25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."
11546,VID_L,LBDVD3LC,LBDVD3LC,25OHD3 comment code,25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS,NaN,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti..."

In [8]:
codebook_select_col = df_sem_duplicatas[['Tabela','Variable_Name', 'SAS_Label', 'Tabela_Valores','English_Text', 'Target']]

In [9]:
codebook_select_col

,Tabela,Variable_Name,SAS_Label,Tabela_Valores,English_Text,Target
0,L02HBS,SEQN,Respondent sequence number,NaN,Respondent sequence number.,Both males and females 2 YEARS - 150 YEARS
1,L02HBS,LBXHBS,Hepatitis B Surface Antibody,"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti...",Hepatitis B surface antibody (anti-HBs),Both males and females 2 YEARS - 150 YEARS
2,L02HPA_A,SEQN,Respondent sequence number,NaN,Respondent sequence number.,Both males and females 2 YEARS - 150 YEARS
3,L02HPA_A,LBXHA,Hepatitis A Antibody (Anti-HAV),"Code.or.Value=[""1"", ""2"", "".""]; Value.Descripti...",Hepatitis A Antibody (Anti-HAV),Both males and females 2 YEARS - 150 YEARS
4,LAB02,SEQN,Respondent sequence number,NaN,Respondent sequence number.,Both males and females 6 YEARS - 150 YEARS
...,...,...,...,...,...,...
11544,VID_L,LBDVD2LC,25OHD2 comment code,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti...",25-hydroxyvitamin D2 comment code,Both males and females 1 YEARS - 150 YEARS
11545,VID_L,LBXVD3MS,25OHD3 (nmol/L),"Code.or.Value=[""4.1 to 422"", "".""]; Value.Descr...",25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS
11546,VID_L,LBDVD3LC,25OHD3 comment code,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti...",25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS
11547,VID_L,LBXVE3MS,epi-25OHD3 (nmol/L),"Code.or.Value=[""0.54 to 62.8"", "".""]; Value.Des...",epi-25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS
11548,VID_L,LBDVE3LC,epi-25OHD3 comment code,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti...",epi-25-hydroxyvitamin D3 comment code,Both males and females 1 YEARS - 150 YEARS

In [10]:
codebook_select_col[codebook_select_col['Variable_Name']=='LBXVD3MS']

,Tabela,Variable_Name,SAS_Label,Tabela_Valores,English_Text,Target
5122,VID_E,LBXVD3MS,25OHD3 (nmol/L),"Code.or.Value=[""3.02 to 212"", "".""]; Value.Desc...",25-hydroxyvitamin D3(nmol/L),Both males and females 1 YEARS - 150 YEARS
6111,VID_F,LBXVD3MS,25OHD3 (nmol/L),"Code.or.Value=[""5.7 to 260"", "".""]; Value.Descr...",25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS
7349,VID_G,LBXVD3MS,25OHD3 (nmol/L),"Code.or.Value=[""5.21 to 373.67"", "".""]; Value.D...",25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS
8741,VID_H,LBXVD3MS,25OHD3 (nmol/L),"Code.or.Value=[""3.05 to 254"", "".""]; Value.Desc...",25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS
10088,VID_I,LBXVD3MS,25OHD3 (nmol/L),"Code.or.Value=[""4.35 to 250"", "".""]; Value.Desc...",25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS
11246,VID_J,LBXVD3MS,25OHD3 (nmol/L),"Code.or.Value=[""6.2 to 421"", "".""]; Value.Descr...",25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS
11545,VID_L,LBXVD3MS,25OHD3 (nmol/L),"Code.or.Value=[""4.1 to 422"", "".""]; Value.Descr...",25-hydroxyvitamin D3 (nmol/L),Both males and females 1 YEARS - 150 YEARS

In [11]:
list_Variable_Name = codebook_select_col['Variable_Name'].unique()
df_codebook_final = pd.DataFrame()

for variable in list_Variable_Name:
    df_now = codebook_select_col[codebook_select_col['Variable_Name']==variable]
    list_english = list(df_now['English_Text'].unique())
    list_Target = list(df_now['Target'].unique())
    df_now['English_Text'] = str(list_english)
    df_now['Target'] = str(list_Target)

    df_codebook_final = pd.concat([df_codebook_final, df_now])

C:\Users\l-oen\AppData\Local\Temp\ipykernel_31332\571734007.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_now['English_Text'] = str(list_english)
C:\Users\l-oen\AppData\Local\Temp\ipykernel_31332\571734007.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_now['Target'] = str(list_Target)

In [12]:
df_codebook_final

,Tabela,Variable_Name,SAS_Label,Tabela_Valores,English_Text,Target
0,L02HBS,SEQN,Respondent sequence number,NaN,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',..."
2,L02HPA_A,SEQN,Respondent sequence number,NaN,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',..."
4,LAB02,SEQN,Respondent sequence number,NaN,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',..."
10,LAB03,SEQN,Respondent sequence number,NaN,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',..."
14,LAB04,SEQN,Respondent sequence number,NaN,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',..."
...,...,...,...,...,...,...
11528,TST_L,LBDLUHLC,Luteinizing Hormone Comment Code,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti...",['Luteinizing Hormone Comment Code'],['Both males and females 6 YEARS - 150 YEARS']
11529,TST_L,LBXPG4,Progesterone (ng/dL),"Code.or.Value=[""0.608 to 12800"", "".""]; Value.D...",['Progesterone (ng/dL)'],['Both males and females 3 YEARS - 150 YEARS']
11530,TST_L,LBDPG4SI,Progesterone (nmol/L),"Code.or.Value=[""0.0193 to 407"", "".""]; Value.De...",['Progesterone (nmol/L)'],['Both males and females 3 YEARS - 150 YEARS']
11531,TST_L,LBDPG4LC,Progesterone Comment Code,"Code.or.Value=[""0"", ""1"", "".""]; Value.Descripti...",['Progesterone Comment Code'],['Both males and females 3 YEARS - 150 YEARS']
11535,TST_L,LBDTSTSI,Testosterone total (nmol/L),"Code.or.Value=[""0.014 to 180"", "".""]; Value.Des...",['Testosterone total (nmol/L)'],['Both males and females 3 YEARS - 150 YEARS']

In [13]:
def process_string_to_dict(string):
    string = string.split('; Count')[0]
    # Substituir os `;` por vírgulas e remover espaços extras
    formatted_string = re.sub(r";", ",", string)
    formatted_string = re.sub(r"=", ":", formatted_string)
    # Adicionar chaves externas para transformá-la em um dicionário
    formatted_string = "{" + formatted_string + "}"
    # Substituir chaves como "Code.or.Value" por "Code" e "Value.Description" por "Description"
    formatted_string = re.sub(r"Code\.or\.Value", '"Code"', formatted_string)
    formatted_string = re.sub(r"Value\.Description", '"Description"', formatted_string)

    return eval(formatted_string)

In [14]:
rows = []
for _, row in df_codebook_final.iterrows():
    # Ignorar linhas onde Tabela_Valores é NaN
    if pd.isna(row['Tabela_Valores']):
        rows.append({
                    "Column": row["Variable_Name"],
                    "Code": None,
                    "Label": None,
                    "English_Text": row["English_Text"],
                    "Target": row["Target"],
                })
        continue
    
    # Extrair os dados de Code e Value.Description
    valores = row['Tabela_Valores']
    
    try:
        # Usando ast.literal_eval para transformar a string em dicionário
        parsed_values = process_string_to_dict(valores)
        codes = parsed_values["Code"]
        codes = [str(item).title() for item in codes]
        descriptions = parsed_values["Description"]
        descriptions = [str(item).title() for item in descriptions]
        # Criar uma nova linha para cada combinação de Code e Description
        for code, description in zip(codes, descriptions):
            rows.append({
                "Column": row["Variable_Name"],
                "Code": code,
                "Label": description,
                "English_Text": row["English_Text"],
                "Target": row["Target"]
            })
    except Exception as e:
        print(f"Erro ao processar a linha: {row['Tabela_Valores']}")
        print(e)

# Criar um novo DataFrame com os dados processados
df_expanded = pd.DataFrame(rows)
df_expanded['Class'] = None
df_expanded['Other For'] = None

Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["428", "188", "1", "234"]; Cumulative=["428", "616", "617", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["526", "103", "1", "221"]; Cumulative=["526", "629", "630", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["521", "101", "0", "229"]; Cumulative=["521", "622", "622", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["531", "86", "0", "234"]; Cumulative=["531", "617", "617", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["180", "440", "0", "231"]; Cumulative=["180", "620", "620", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["218", "65", "3", "565"]; Cumulative=["218", "283", "286", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["190", "2827", "0", "249"]; Cumulative=["190", "3017", "3017", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["251", "79", "0", "521"]; Cumulative=["251", "330", "330", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["271", "2698", "0", "297"]; Cumulative=["271", "2969", "2969", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["336", "18", "0", "497"]; Cumulative=["336", "354", "354", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["528", "2475", "0", "263"]; Cumulative=["528", "3003", "3003", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["300", "0", "0", "551"]; Cumulative=["300", "300", "300", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["1441", "1525", "0", "300"]; Cumulative=["1441", "2966", "2966", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["253", "0", "2", "596"]; Cumulative=["253", "253", "255", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["1688", "1217", "0", "361"]; Cumulative=["1688", "2905", "2905", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["303", "47", "0", "501"]; Cumulative=["303", "350", "350", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["441", "2573", "0", "252"]; Cumulative=["441", "3014", "3014", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["87", "200", "0", "564"]; Cumulative=["87", "287", "287", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["21", "2973", "0", "272"]; Cumulative=["21", "2994", "2994", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["253", "34", "17", "547"]; Cumulative=["253", "287", "304", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["1595", "1400", "0", "271"]; Cumulative=["1595", "2995", "2995", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Lilmit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["235", "26", "1", "589"]; Cumulative=["235", "261", "262", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["1095", "1893", "0", "278"]; Cumulative=["1095", "2988", "2988", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["247", "4", "33", "567"]; Cumulative=["247", "251", "284", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["133", "2653", "0", "480"]; Cumulative=["133", "2786", "2786", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["180", "128", "1", "542"]; Cumulative=["180", "308", "309", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["1007", "1987", "0", "272"]; Cumulative=["1007", "2994", "2994", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["268", "15", "1", "567"]; Cumulative=["268", "283", "284", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["34", "268", "1", "548"]; Cumulative=["34", "302", "303", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["20", "2997", "0", "249"]; Cumulative=["20", "3017", "3017", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["11", "274", "1", "565"]; Cumulative=["11", "285", "286", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["294", "4", "6", "547"]; Cumulative=["294", "298", "304", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["2907", "91", "0", "268"]; Cumulative=["2907", "2998", "2998", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["Detectable Result", "Below Detectable Limit", "Detectable Result and Exceeds the Calibrated Range of
      Assay", "Missing"]; Count=["284", "10", "2", "555"]; Cumulative=["284", "294", "296", "851"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["2047", "966", "0", "253"]; Cumulative=["2047", "3013", "3013", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["1", "2934", "0", "331"]; Cumulative=["1", "2935", "2935", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["101", "2869", "0", "296"]; Cumulative=["101", "2970", "2970", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["0", "2970", "0", "296"]; Cumulative=["0", "2970", "2970", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["2", "2994", "0", "270"]; Cumulative=["2", "2996", "2996", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["13", "2940", "0", "313"]; Cumulative=["13", "2953", "2953", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["22", "2984", "0", "260"]; Cumulative=["22", "3006", "3006", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["874", "2136", "0", "256"]; Cumulative=["874", "3010", "3010", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["0", "2969", "0", "297"]; Cumulative=["0", "2969", "2969", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["0", "3009", "0", "257"]; Cumulative=["0", "3009", "3009", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["0", "2906", "0", "360"]; Cumulative=["0", "2906", "2906", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["718", "2299", "0", "249"]; Cumulative=["718", "3017", "3017", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["9", "2974", "0", "283"]; Cumulative=["9", "2983", "2983", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["0", "2963", "0", "303"]; Cumulative=["0", "2963", "2963", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["19", "2753", "0", "494"]; Cumulative=["19", "2772", "2772", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]
unterminated string literal (detected at line 1) (<string>, line 1)
Erro ao processar a linha: Code.or.Value=["0", "1", "2", "."]; Value.Description=["At or above detection limit", "Below lower detection limit", "Detectable result and exceeds the calibrated range of
      assay", "Missing"]; Count=["0", "2884", "0", "382"]; Cumulative=["0", "2884", "2884", "3266"]; Skip.to.Item=["NA", "NA", "NA", "NA"]

In [15]:
df_expanded

,Column,Code,Label,English_Text,Target,Class,Other For
0,SEQN,None,None,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',...",None,None
1,SEQN,None,None,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',...",None,None
2,SEQN,None,None,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',...",None,None
3,SEQN,None,None,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',...",None,None
4,SEQN,None,None,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',...",None,None
...,...,...,...,...,...,...,...
28867,LBDPG4LC,0,At Or Above The Detection Limit,['Progesterone Comment Code'],['Both males and females 3 YEARS - 150 YEARS'],None,None
28868,LBDPG4LC,1,Below Lower Detection Limit,['Progesterone Comment Code'],['Both males and females 3 YEARS - 150 YEARS'],None,None
28869,LBDPG4LC,.,Missing,['Progesterone Comment Code'],['Both males and females 3 YEARS - 150 YEARS'],None,None
28870,LBDTSTSI,0.014 To 180,Range Of Values,['Testosterone total (nmol/L)'],['Both males and females 3 YEARS - 150 YEARS'],None,None
28871,LBDTSTSI,.,Missing,['Testosterone total (nmol/L)'],['Both males and females 3 YEARS - 150 YEARS'],None,None

In [16]:
df_expanded.drop_duplicates(inplace=True)

In [17]:
df_expanded

,Column,Code,Label,English_Text,Target,Class,Other For
0,SEQN,None,None,"['Respondent sequence number.', 'Respondent se...","['Both males and females 2 YEARS - 150 YEARS',...",None,None
720,LBXHBS,1,Positive,"['Hepatitis B surface antibody (anti-HBs)', 'H...",['Both males and females 2 YEARS - 150 YEARS'],None,None
721,LBXHBS,2,Negative,"['Hepatitis B surface antibody (anti-HBs)', 'H...",['Both males and females 2 YEARS - 150 YEARS'],None,None
722,LBXHBS,.,Missing,"['Hepatitis B surface antibody (anti-HBs)', 'H...",['Both males and females 2 YEARS - 150 YEARS'],None,None
746,LBXHBS,3,Indeterminate,"['Hepatitis B surface antibody (anti-HBs)', 'H...",['Both males and females 2 YEARS - 150 YEARS'],None,None
...,...,...,...,...,...,...,...
28867,LBDPG4LC,0,At Or Above The Detection Limit,['Progesterone Comment Code'],['Both males and females 3 YEARS - 150 YEARS'],None,None
28868,LBDPG4LC,1,Below Lower Detection Limit,['Progesterone Comment Code'],['Both males and females 3 YEARS - 150 YEARS'],None,None
28869,LBDPG4LC,.,Missing,['Progesterone Comment Code'],['Both males and females 3 YEARS - 150 YEARS'],None,None
28870,LBDTSTSI,0.014 To 180,Range Of Values,['Testosterone total (nmol/L)'],['Both males and females 3 YEARS - 150 YEARS'],None,None
28871,LBDTSTSI,.,Missing,['Testosterone total (nmol/L)'],['Both males and females 3 YEARS - 150 YEARS'],None,None

In [18]:
variable = list(df_expanded['Column'].unique())

In [19]:
variable[200:210]

['LBXTO5IN',
 'LBXSAL',
 'LBDSALSI',
 'LBXSATSI',
 'LBXSASSI',
 'LBXSAPSI',
 'LBXSBU',
 'LBDSBUSI',
 'LBXSCA',
 'LBDSCASI']

In [20]:
df_expanded[df_expanded['Column']=='LBXSAL']

,Column,Code,Label,English_Text,Target,Class,Other For
3975,LBXSAL,1.2 To 5.7,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3976,LBXSAL,.,Missing,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3977,LBXSAL,2.1 To 5.5,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3979,LBXSAL,1.9 To 5.5,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3981,LBXSAL,2.3 To 5.4,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3983,LBXSAL,1.2 To 5.5,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3985,LBXSAL,2.5 To 5.3,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3989,LBXSAL,2.4 To 5.6,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3991,LBXSAL,2 To 5.6,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3993,LBXSAL,2.1 To 5.4,Range Of Values,"['Albumin (g/dL)', 'Albumin refrigerated serum...",['Both males and females 12 YEARS - 150 YEARS'],None,None

In [21]:
df_expanded[df_expanded['Column']=='LBDSALSI']

,Column,Code,Label,English_Text,Target,Class,Other For
3997,LBDSALSI,12 To 57,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3998,LBDSALSI,.,Missing,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
3999,LBDSALSI,21 To 55,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
4001,LBDSALSI,19 To 55,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
4003,LBDSALSI,23 To 54,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
4005,LBDSALSI,12 To 55,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
4007,LBDSALSI,25 To 53,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
4011,LBDSALSI,24 To 56,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
4013,LBDSALSI,20 To 56,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None
4015,LBDSALSI,21 To 54,Range Of Values,"['Albumin (g/L)', 'Albumin refrigerated serum(...",['Both males and females 12 YEARS - 150 YEARS'],None,None

In [22]:
df_expanded.to_csv('LAB_codebook.csv', sep=',', encoding='utf-8')

In [23]:
dictionary_mapping = codebook_select_col[['Variable_Name']]

In [24]:
dictionary_mapping = dictionary_mapping.drop_duplicates(subset='Variable_Name', keep='first')

In [25]:
dictionary_mapping['Attribute'] = None
dictionary_mapping['attributeOf'] = None
dictionary_mapping['Unit'] = None
dictionary_mapping['Time'] = None
dictionary_mapping['Entity'] = None
dictionary_mapping['Role'] = None
dictionary_mapping['Relation'] = None
dictionary_mapping['inRelationTo'] = None
dictionary_mapping['wasDerivedFrom'] = None
dictionary_mapping['wasGeneratedBy'] = None

In [26]:
dictionary_mapping.reset_index(inplace=True, drop=True)

In [27]:
dictionary_mapping

,Variable_Name,Attribute,attributeOf,Unit,Time,Entity,Role,Relation,inRelationTo,wasDerivedFrom,wasGeneratedBy
0,SEQN,None,None,None,None,None,None,None,None,None,None
1,LBXHBS,None,None,None,None,None,None,None,None,None,None
2,LBXHA,None,None,None,None,None,None,None,None,None,None
3,LBXHBC,None,None,None,None,None,None,None,None,None,None
4,LBDHBG,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
2921,LBDLUHLC,None,None,None,None,None,None,None,None,None,None
2922,LBXPG4,None,None,None,None,None,None,None,None,None,None
2923,LBDPG4SI,None,None,None,None,None,None,None,None,None,None
2924,LBDPG4LC,None,None,None,None,None,None,None,None,None,None
2925,LBDTSTSI,None,None,None,None,None,None,None,None,None,None

In [28]:
dictionary_mapping.rename(columns={"Variable_Name": "Column"}, inplace=True)

In [29]:
dictionary_mapping.to_csv('LAB_dictionary_mapping.csv', sep=',', encoding='utf-8')